import Head from "next/head";
import { Box, Container, useColorMode } from "@chakra-ui/react";
import LandingPage from "../components/LandingPage/LandingPage";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Box py={10}>
      <Head>
        <title>Validator Bootstrap</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </Box>
    // <Container maxW="5xl" py={10}>
    //   <Head>
    //     <title>Validator Bootstrap</title>
    //     <meta name="description" content="Generated by create cosmos app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <LandingPage />
    // </Container>
  );
}
