import Head from "next/head";
import { Container, useColorMode } from "@chakra-ui/react";

import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { Product, Dependency, WalletSection } from "../components";
import { dependencies, products } from "../config";
import { ValidatorsTable } from "../components/ValidatorsTable/ValidatorsTable";
import { Route } from "react-router-dom";
import { Box, Text, Button } from "grommet";
import Link from "next/link";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Validator Bootstrap</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box align="center">
        <Box gap="medium">
          <Text>Validator Bootstrap</Text>
          <Box>Description goes here!!</Box>
        </Box>
        <Box gap="small" direction="row">
          <Button label="Create a new campaign" />
          <Button as={Link} href="/campaigns" label="Participate to pledge" />
        </Box>
      </Box>
    </Container>
  );
}
